services:
  devbuntu:
    image: auguryan/devbuntu:latest
    container_name: devbuntu
    tty: true
    stdin_open: true
    privileged: true
    volumes:
      - code:/mnt/code
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30

volumes:
  code:
    driver: hetzner
    driver_opts:
      size: 10
  cache:
    driver: hetzner
    driver_opts:
      size: 10
